### ISSUE TITLE
The cards are not smooth

### ISSUE THREAD

**Issue by crichmond1989** [bladeSk/readabletro#1]
The font looks good. It seems like the smooth effect was simply not applied to cards.

Deck: Checkered
OS: Windows 11 Home
Version: 10.0.22631 Build 22631
Extracted path: C:\Program Files (x86)\Steam\steamapps\common\Balatro

![image](https://github.com/bladeSk/readabletro/assets/29367357/80bb4550-daf7-41d9-90c8-5cd5fdd3276f)

**Comment by bladeSk** [comment]
You need to enable "Pixel art smoothing" in graphics settings.
![image](https://github.com/bladeSk/readabletro/assets/4263742/9c9607a4-88ac-4fd4-a7f4-3cd0a372460a)

**Comment by crichmond1989** [comment]
Still fuzzy.

I've tried windowed at 2560x1440 and fullscreen at 5120x1440.

![image](https://github.com/bladeSk/readabletro/assets/29367357/5391a182-9034-47ef-bfed-c97ab6e6b48d)

**Comment by crichmond1989** [comment]
Hmm, the zip does not have files in resources/textures/2x. Maybe that's off? I'll try cloning and copying them over.

**Comment by crichmond1989** [comment]
Sweet. That fixed it!

Full steps:

1. Download zip from here: https://github.com/bladeSk/readabletro/releases/tag/1.0.0n
2. Extract into game folder
3. Clone project via "download zip"
4. Copy resources/textures/2x/* files into the same spot in the game folder
5. Run apply_readabletro.cmd

**Comment by bladeSk** [comment]
Dang, the zip file is missing the images. I'll fix that when I get back home. Thanks for reporting the issue.

**Comment by bladeSk** [comment]
Alright, the CI script is fixed, the zip file should now contain all the required files.
