### ISSUE TITLE
"Couldn't find Balatro.exe. Copy these files to Balatro's game directory and run apply_readabletro.cmd again."

### ISSUE THREAD

**Issue by MultiKoopa** [bladeSk/readabletro#2]
Windows 11 64-bit, copied all the files to the game's directory, literally right next to the EXE; ran as administrator; doesn't work.

Any ideas?

**Comment by bladeSk** [comment]
I'll need more details. Can you send the output of the console window?

**Comment by MultiKoopa** [comment]
> I'll need more details. Can you send the output of the console window?

![image](https://github.com/bladeSk/readabletro/assets/30543543/33c85600-8015-4918-aa33-ee65d8e9b1bc)

that's.... that's it.

**Comment by bladeSk** [comment]
OK, I see what the problem is, Windows messes up the working directory when you run a cmd file as admin. I added a workaround for this, try the [new version](https://github.com/bladeSk/readabletro/releases/latest).
