### ISSUE TITLE
Steam Deck: Cursor/Selector getting stuck between rounds

### ISSUE THREAD

**Issue by ronnierage** [bladeSk/readabletro#4]
While using either the d-pad or joystick to navigate options between rounds (shop, blinds, and possibly more), navigating to the far right to select the card deck results in getting stuck. I am unable to use the d-pad or joystick to navigate back off of the deck. I must either use the track pad or touchscreen to move off of it.

**Comment by bladeSk** [comment]
Can you verify this doesn't happen in the unmodified version?

**Comment by ronnierage** [comment]
Yes, I can verify that this does not happen in the unmodified version.

Also, I'd like to add that I am experiencing this issue with the standalone
EXE that I downloaded from the MediaFire link in your Reddit post.

**Comment by bladeSk** [comment]
I can't reproduce the issue, but I know what you're talking about, it's happened to me too. I suspect very specific contitions must be met, like a specific number of cards, aspect ratio, etc. Readabletro uses a different font, so some elements are in slightly different places. Tracking down the issue sounds like a debugging nightmare. 🥲

As a workaround, you can use the right stick to move the cursor, when this happens.

**Comment by ronnierage** [comment]
Issue seems to come and go.  Can't reliably reproduce, but still randomly experience it.  The right stick workaround works well enough.
