### ISSUE TITLE
Steam Deck: READABLETRO high contrast darker than vinilla high contrast

### ISSUE THREAD

**Issue by ronnierage** [bladeSk/readabletro#5]
As title suggests, after applying readabletro, the high contrast colors are noticeably darker than the vanilla high contrast colors.

READABLETRO:
![READABLETRO](https://github.com/user-attachments/assets/e6f17edc-80e1-4bc2-8ed0-6727878d8970)

VANILLA:
![VANILLA](https://github.com/user-attachments/assets/9337e057-d854-4fab-abde-f096beeb155d)

**Comment by bladeSk** [comment]
Yes, I removed the gradients from the high contrast deck to increase the contrast further. Feel free to customize the mod to your liking.
